django_shop/django_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path("api/v2/", include("shop.rest_api")),
    path("jet/", include("jet.urls", "jet")),  # Django JET URLS
    path("jet/dashboard/", include("jet.dashboard.urls", "jet-dashboard")),
    path("admin/", admin.site.urls),
    path("shop/", include("shop.urls")),
    # path("users/", include(("users.urls", "users"), namespace="users")),
    path("users/", include("users.urls")),
    path("payment/", include("payment.urls")),
    path("select2/", include("django_select2.urls")),
]

django_shop/shop/urls.py
from django.urls import path, re_path, reverse
from users.views import profile
from shop import views
from shop.views import general
from shop.views import cart

urlpatterns = [
    path("", general.index, name="index"),
    # path("books/", views.BookListView.as_view(), name="books"),
    path(
        "product/<int:pk>/", general.ProductDetailView.as_view(), name="product-detail"
    ),
    path("cart/detail/", views.cart.cart_detail, name="cart-detail"),
    path("list/add/", general.ListCreateView.as_view(), name="list-create"),
    path("list/<int:pk>/", general.ListDetailView.as_view(), name="list-detail"),
    path("api/get-product/<int:pk>/", general.get_product, name="product-api"),
    path("ajax/add-item-to-list/", general.add_item_to_list, name="add-item-to-list"),
    path(
        "ajax/remove-item-from-cart/",
        cart.remove_item_from_cart,
        name="remove-item-from-cart",
    ),
    path("ajax/add-item-to-cart/", cart.add_item_to_cart, name="add-item-to-cart"),
    path("ajax/reload-cart-items/", cart.reload_cart_items, name="reload-cart-items"),
    path("ajax/update_cart_items/", cart.update_cart_items, name="update-cart-items"),
    path("proceed-to-buy/", cart.proceed_to_buy, name="proceed-to-buy"),
    path("categories/", general.CategoryListView.as_view(), name="category-list"),
    path(
        "categories/<slug:slug>/",
        general.CategoryDetailView.as_view(),
        name="category-detail",
    ),
    path("<slug:username>/", general.show_user_lists, name="user-lists"),
    # for something like 'the-secret-garden' as slug
    # re_path(r'^book/(?P<stub>[-\w]+)$', views.BookDetailView.as_view(), name='book-detail'),
    # urls can have additional options
    # path('url/', views.my_reused_view, {'my_template_name': 'some_path'}, name='aurl'),
    # path('anotherurl/', views.my_reused_view, {'my_template_name': 'another_path'}, name='anotherurl'),
]

django_shop/shop/models/fields.py
from django.conf import settings

postgresql_engine_names = [
    "django.db.backends.postgresql",
    "django.db.backends.postgresql_psycopg2",
]


if settings.DATABASES["default"]["ENGINE"] in postgresql_engine_names:
    from django.contrib.postgres.fields import JSONField as _JSONField
else:
    from jsonfield.fields import JSONField as _JSONField


class JSONField(_JSONField):
    def __init__(self, *args, **kwargs):
        kwargs.update({"default": {}})
        super(JSONField, self).__init__(*args, **kwargs)

    def deconstruct(self):
        name, path, args, kwargs = super(JSONField, self).deconstruct()
        del kwargs["default"]

        return name, path, args, kwargs

django_shop/shop/models/product.py
from django.db import models
from django.urls import reverse

from functools import reduce
import operator
from datetime import datetime
from django.utils.translation import ugettext_lazy as _
from django.apps import apps

from shop import models as shop_models

from shop.models.cart import CartListItem


class ProductManager(models.Manager):
    def select_lookup(self, search_term):
        """
        Returning a queryset containing the products matching the declared lookup fields together
        with the given search term. Each product can define its own lookup fields using the
        member list or tuple `lookup_fields`.
        """
        filter_by_term = (
            models.Q((sf, search_term)) for sf in self.model.lookup_fields
        )
        queryset = self.get_queryset().filter(reduce(operator.or_, filter_by_term))
        return queryset

    def indexable(self):
        """
        Return a queryset of indexable Products.
        """
        queryset = self.get_queryset().filter(active=True)
        return queryset

    def by_cart(self, cart):
        queryset = self.get_queryset().filter(lists__carts=cart)


class IntegerRangeField(models.IntegerField):
    def __init__(
        self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs
    ):
        self.min_value, self.max_value = min_value, max_value
        models.IntegerField.__init__(self, verbose_name, name, **kwargs)

    def formfield(self, **kwargs):
        defaults = {"min_value": self.min_value, "max_value": self.max_value}
        defaults.update(kwargs)
        return super(IntegerRangeField, self).formfield(**defaults)


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("category-detail", args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    item_id = models.CharField(max_length=100)
    url = models.CharField(max_length=300)
    price = models.IntegerField()
    discount = IntegerRangeField(min_value=0, max_value=100)
    photo_url = models.CharField(max_length=255)
    available = models.BooleanField(default=True, blank=True)
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)

    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)

    active = models.BooleanField(
        _("Active"), default=True, help_text=_("Is this product publicly visible.")
    )

    objects = ProductManager()

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def is_in_cart(self, cart):
        cart_item_qs = CartListItem.objects.filter(cart=cart, list_item__product=self)
        return cart_item_qs.first()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("product-detail", args=[self.id])

django_shop/shop/views/address.py
from django.db import transaction

from rest_framework import status
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.renderers import BrowsableAPIRenderer

from shop.models.address import ShippingAddress, BillingAddress
from shop.models.cart import Cart


class AddressEditView(GenericAPIView):
    """
    View class to render associated addresses for the current user.
    """

    renderer_classes = (BrowsableAPIRenderer,)
    permission_classes = (IsAuthenticated,)
    form_class = None  # must be overridde

    def __init__(self, **kwargs):
        super(AddressEditView, self).__init__(**kwargs)
        self.visible_fields = [f.name for f in self.form_class().visible_fields()]

    def get(self, request, priority=None, *args, **kwargs):
        if priority == "add":
            # deliver an empty form
            form = self.form_class()
        else:
            try:
                if self.form_class.__name__ == "BillingAddressForm":
                    instance = request.customer.billingaddress_set.get(
                        priority=priority
                    )
                elif self.form_class.__name__ == "ShippingAddressForm":
                    instance = request.customer.shippingaddress_set.get(
                        priority=priority
                    )
                else:
                    raise Cart.DoesNotExist()
            except (ShippingAddress.DoesNotExist, BillingAddress.DoesNotExist):
                return Response(status=status.HTTP_410_GONE)
            else:
                cart = Cart.objects.get_from_request(request)
                form = self.form_class(instance=instance, cart=cart)
        initial_data = dict(
            (k, v)
            for k, v in form.get_initial_data().items()
            if k in self.visible_fields
        )
        initial_data.pop("use_primary_address", None)
        return Response({self.form_class.form_name: initial_data})

    def put(self, request, *args, **kwargs):
        data = request.data.get(self.form_class.scope_prefix, {})
        cart = Cart.objects.get_from_request(request)
        form = self.form_class(data=data, cart=cart)
        if form.is_valid():
            return Response()
        response_data = {self.form_class.form_name: dict(errors=form.errors)}
        return Response(response_data, status=status.HTTP_422_UNPROCESSABLE_ENTITY)

    def delete(self, request, priority=None, *args, **kwargs):
        cart = Cart.objects.get_from_request(request)
        with transaction.atomic():
            try:
                if self.form_class.__name__ == "BillingAddressForm":
                    request.customer.billingaddress_set.get(priority=priority).delete()
                elif self.form_class.__name__ == "ShippingAddressForm":
                    request.customer.shippingaddress_set.get(priority=priority).delete()
            except (
                ValueError,
                ShippingAddress.DoesNotExist,
                BillingAddress.DoesNotExist,
            ):
                pass

            # take the last of the remaining addresses
            if self.form_class.__name__ == "BillingAddressForm":
                instance = request.customer.billingaddress_set.last()
                cart.billing_address = instance
            elif self.form_class.__name__ == "ShippingAddressForm":
                instance = request.customer.shippingaddress_set.last()
                cart.shipping_address = instance
            cart.save()

        # repopulate the form with address fields from the last remaining address
        if instance:
            form = self.form_class(instance=instance, cart=cart)
            initial_data = dict(
                (k, v)
                for k, v in form.get_initial_data().items()
                if k in self.visible_fields
            )
            initial_data.update(
                active_priority=str(instance.priority),
                siblings_summary=form.siblings_summary,
            )
            return Response({self.form_class.form_name: initial_data})
        return Response(status=status.HTTP_410_GONE)

django_shop/shop/views/cart.py
from django.utils.cache import add_never_cache_headers
from rest_framework import status, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from shop.models.cart import Cart, CartListItem
from shop.models.product import Product
from shop.models.list import ListItem, List
from shop.models.customer import Customer
from shop.serializers.cart import CartSerializer, CartListItemSerializer
from django.shortcuts import render
from shop.serializers.product import ProductSerializer
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.http import HttpResponse
from django.contrib import messages


def cart_detail(request):
    cart = Cart.objects.get_or_create_from_request(request)
    return render(request, "shop/cart_detail.html", context={"cart": cart})


def remove_item_from_cart(request):
    id_ = request.GET.get("id")
    cart = Cart.objects.get_or_create_from_request(request)

    CartListItem.objects.get(id=id_).delete()
    messages.success(request, f"Item removed from your cart")

    django_messages = []

    for message in messages.get_messages(request):
        django_messages.append(
            {"level": message.level, "message": message.message, "tags": message.tags}
        )

    data = {}
    data["success"] = "ok"
    data["messages"] = django_messages
    return JsonResponse(data)


def add_item_to_cart(request):
    id_ = request.GET.get("id")
    pk = int(request.GET.get("pk"))
    print(type(pk))
    p = Product.objects.get(id=id_)
    print(pk)
    print(List.objects.get(id=pk))

    list_item = ListItem.objects.get(product=p, llist=List.objects.get(id=pk))
    cart = Cart.objects.get_or_create_from_request(request)

    CartListItem.objects.get_or_create(cart=cart, list_item=list_item, quantity=1)
    # items are not added to CART! #TODO:
    messages.success(request, f"Item added to your cart")

    django_messages = []

    for message in messages.get_messages(request):
        django_messages.append(
            {"level": message.level, "message": message.message, "tags": message.tags}
        )

    data = {}
    data["success"] = "ok"
    data["messages"] = django_messages
    return JsonResponse(data)


def update_cart_items(request):
    # cart = Cart.objects.get_from_request(request)
    # product_list = Products.objects.by_cart(cart=cart)
    customer = Customer.objects.get_from_request(request)
    return render(request, "shop/load_cart.html", {"customer": customer})


def reload_cart_items(request):
    cart = Cart.objects.get_or_create_from_request(request)
    return render(request, "shop/cart_items_detail.html", {"cart": cart})


def proceed_to_buy(request):
    # check for login type!
    if request.customer.is_authenticated:
        return render(request, "shop/start_buying_summary_page.html")
    else:
        if request.customer.is_guest:
            return HttpResponse(
                "<html><body>YOU ARE GUEST!<br>NOT AUTHENTICATED! AUTHENTICATE YOURSELF!</body></html>"
            )
        elif request.customer.is_recognized:
            return HttpResponse(
                "<html><body>YOU ARE RECOGNIZED!<br>NOT AUTHENTICATED! AUTHENTICATE YOURSELF!</body></html>"
            )
        else:
            return HttpResponse(
                f"<html><body>YOU ARE NOT RECOGNIZED!<br>{request.customer.recognized}NOT AUTHENTICATED! AUTHENTICATE YOURSELF!</body></html>"
            )


# class CartViewSet(viewsets.ModelViewSet):
#     serializer_label = "cart"
#     serializer_class = CartSerializer
#     item_serializer_class = CartItemSerializer

#     pagination_class = None

#     def get_queryset(self):
#         try:
#             cart = Cart.objects.get_from_request(self.request)
#             if self.kwargs.get(self.lookup_field):
#                 # we're interest only into a certain cart item
#                 return CartItem.objects.filter(cart=cart)
#             return cart
#         except Cart.DoesNotExist:
#             return Cart()

#     def list(self, request, *args, **kwargs):
#         cart = self.get_queryset()
#         context = self.get_serializer_context()
#         serializer = self.serializer_class(
#             cart, context=context, label=self.serializer_label
#         )
#         return Response(serializer.data)

#     def create(self, request, *args, **kwargs):
#         """
#         Create a new item in the cart.
#         """
#         context = self.get_serializer_context()
#         item_serializer = self.item_serializer_class(
#             context=context, data=request.data, label=self.serializer_label
#         )
#         item_serializer.is_valid(raise_exception=True)
#         self.perform_create(item_serializer)
#         headers = self.get_success_headers(item_serializer.data)
#         return Response(
#             item_serializer.data, status=status.HTTP_201_CREATED, headers=headers
#         )

#     def update(self, request, *args, **kwargs):
#         """
#         Handle changing the amount of the cart item referred by its primary key.
#         """
#         cart_item = self.get_object()
#         context = self.get_serializer_context()
#         item_serializer = self.item_serializer_class(
#             cart_item, context=context, data=request.data, label=self.serializer_label
#         )
#         item_serializer.is_valid(raise_exception=True)
#         self.perform_update(item_serializer)
#         cart_serializer = CartSerializer(cart_item.cart, context=context, label="cart")
#         response_data = {
#             "cart_item": item_serializer.data,
#             "cart": cart_serializer.data,
#         }
#         return Response(data=response_data)

#     def destroy(self, request, *args, **kwargs):
#         """
#         Delete a cart item referred by its primary key.
#         """
#         cart_item = self.get_object()
#         context = self.get_serializer_context()
#         cart_serializer = CartSerializer(
#             cart_item.cart, context=context, label=self.serializer_label
#         )
#         self.perform_destroy(cart_item)
#         response_data = {"cart_item": None, "cart": cart_serializer.data}
#         return Response(data=response_data)

#     @action(detail=True, methods=["get"])
#     def fetch(self, request):
#         cart = self.get_queryset()
#         context = self.get_serializer_context()
#         serializer = self.serializer_class(cart, context=context)
#         return Response(serializer.data)

#     @action(detail=False, methods=["get"], url_path="fetch-dropdown")
#     def fetch_dropdown(self, request):
#         cart = self.get_queryset()
#         context = self.get_serializer_context()
#         serializer = self.serializer_class(cart, context=context, label="dropdown")
#         return Response(serializer.data)

django_shop/shop/templates/shop/cart_detail.html
{% extends "shop/base.html" %}
{% load i18n %}
{% block content %}

  {{cart.customer}}
  
<div class="row">
    <table class='table table-hover table-bordered'>
        <thead class='thead-dark'>
        <tr>
                <th scope='col'>select</th>
                <th scope='col'>#</th>
                <th scope='col'>Name</th>
                <th scope='col'>URL of item</th>
                <th scope='col'>URL of source</th>
                <th scope='col'>Price</th>
                <th scope='col'>Image</th>
            </tr>
    </thead>

    <tbody>
    {%include 'shop/cart_items_detail.html'%}
    </tbody>
    </table>

</div>
{% endblock content %}
{%block scripts%}
    <script>
          function update_messages(m){  
            $("#messages_div").html("");
            $("#messages_div").append("<div class='alert alert-"+m.tags+"'>"+m.message+"</div>");
        };
        function reload_items(){  
          console.log("hello" )
          $('#cart-menu').html('').load(
              "{% url 'reload-cart-items' %}"
          );
        };


    $(".remove-item").click(function () {
      var id = $(this).attr('value');
      console.log($(this).parent())
      $.ajax({
        url: '/shop/ajax/remove-item-from-cart/',
        data: {
          'id': id
        },
        dataType: 'json',
        success: function (data) {
          if (data.success) {
            console.log(data.messages[0])
            console.log(data.messages[0].level)
            console.log(data.messages[0].message)
            console.log("<div class='alert alert-"+data.messages[0].tags+"'>"+data.messages[0].message+"</div>")
            update_messages(data.messages[0]);
            reload_items();
          }
        }
      });

    });
  </script>
{%endblock scripts%}

django_shop/shop/templates/shop/cart_items_detail.html
{% for list_item in cart.list_items.all %}
        <tr>
            <th scope='row'><button class="remove-item" value="{{ list_item.id }}">remove</button></td>
            <td >{{forloop.counter}}</th>
            <td>{{list_item.product.name}}</th>
            <td><a href="{% url 'product-detail' list_item.product.id %}" class="">product page</a></th>
            <td><a href="http://www.digikala.com/{{list_item.product.url}}">details</a></th>
            <td>{{list_item.product.price}}</th>
            <td><img class='img-thumbnail' src="{{list_item.product.photo_url}}" width='48px'></th>
        </tr>
{% endfor %}

django_shop/shop/templates/shop/category_detail.html
{% extends "shop/base.html" %}
{% load i18n %}
{% block content %}
<div class="row">
  {% for product in object.product_set.all %}
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <a href="#"><img class="card-img-top" src="{{product.photo_url}}" alt=""></a>
        <div class="card-body">
          <div class='card-desc-wrap'>
            <h6 class="card-title">
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
          </h6>
          <p class="card-text">
            <p>{{product.price}}</p>
          </p>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock content %}

django_shop/shop/templates/shop/category_list.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block content %}

<h1>{% trans "Category List" %}</h1>

{% if category_list %}
  <div class="accordion" id="accordionCategoryList">
  {% for category in category_list %}
    <div class="card" >
      <div class="cardheader" id="heading{{forloop.counter}}">
        <h5 class="mb-0">
          <button class="btn btn-link" type='button' data-toggle="collapse" data-target="#collapse{{forloop.counter}}" aria-expanded="true" aria-controls="collapse{{forloop.counter}}">
            <a href="{{ category.get_absolute_url }}">
              {{ category.name }}
            </a>
          </button>
        </h5>
      </div>
      <div id="collapse{{forloop.counter}}" class="collapse" aria-labelledby="heading{{forloop.counter}}" data-parent="#accordionCategoryList">
        <div class="card-body">
          {% for product in category.product_set.all|slice:":10" %}
            <div class="row mt-1">
              <div class="col-md-1">
                <img class="img-fluid" width="64px" src="{{ product.photo_url }}">
              </div>
              <div class="cold-md-11">
                <p><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>
              </div>
            </div>
          {% endfor %}
          <div class="row mt-1">
              <div class="col-md-10">
                <img class="img-fluid" width="64px" src="{{ product.photo_url }}">
              </div>
              <div class="cold-md-2">
                <p><a href="{{ category.get_absolute_url }}">مشاهده همه</a></p>
              </div>
            </div>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>
{% else %}
  <p>There are no categories available.</p>
{% endif %}

{% endblock %}

django_shop/shop/templates/shop/index.html
{% extends "shop/base.html" %}
{% load i18n %}


{% block title %}<title>{% trans "Index Page" %}</title>{% endblock %}


{% block content %}
<div class="row">
  {% if not request.user.is_authenticated %}
  <div class="col-md-6">
    <p><a href="{% url 'login' %}" class="">login</a> if you want to create a list</p>
  </div>
  {% else %}
  <div class="col-md-12">
    <p class="">you can create a list now</p>
    <p> or </p>
    <p> change your previously added lists: </p>
    <div class="row">
    <div class="col-md-12 list-group">
      {% for list in user.lists.all %}
        <a href="{% url 'list-detail' list.id %}" class="text-center list-group-item list-group-item-action list-group-item-primary">{{list.name}}</a>  
      {% endfor %}
    </div>
    </div>
  </div>


  {% endif %}
</div>
{% endblock content %}

django_shop/shop/templates/shop/list_detail.html
{% extends 'shop/base.html' %} 
{%block content %}
<h1>{{ object.name }}</h1>
<p>{{ object.description }}</p>

    <table class='table table-hover table-bordered'>
        <thead class='thead-dark'>
        <tr>
                <th scope='col'>#</th>
                <th scope='col'>Name</th>
                <th scope='col'>URL of item</th>
                <th scope='col'>URL of source</th>
                <th scope='col'>Price</th>
                <th scope='col'>Image</th>
                <th scope='col'></th>
                
            </tr>
    </thead>

    <tbody>
    {% for product in object.products.all %}
            <tr>
                <th scope='row'>{{forloop.counter}}</th>
                <td>{{product.name}}</th>
                <td><a href="{% url 'product-detail' product.id %}" class="">product page</a></th>
                <td><a href="http://www.digikala.com/{{product.url}}">details</a></th>
                <td>{{product.price}}</th>
                <td><img class='img-thumbnail' src="{{product.photo_url}}" width='48px'></th>
                <td ><button class='add-to-cart btn btn-success btn-block btn-sm no-wrap' value="{{ product.id }}">add to cart</button></td>
                
            </tr>
        
    {% endfor %}
    </tbody>
    </table>
<a href="{% url 'user-lists' object.owner.username %}" class="">{{object.owner.username}}'s lists</a>


{%endblock content %}


{%block scripts%}
    <script>
        function update_messages(m){  
            $("#messages_div").html("");
            $("#messages_div").append("<div class='alert alert-"+m.tags+"'>"+m.message+"</div>");
        };
        function update_cart(p){  
            $("#cart-menu").append("<a class='dropdown-item' href='#'>"+p.name+"</a>");
        };
        function update_cart_items() {
          console.log("hello" )
          $('#cart-menu').html('').load(
              "{% url 'update-cart-items' %}"
          );
        };

    $(".add-to-cart").click(function () {
      var id = $(this).attr('value');
      var url = document.URL;
      url = url.split('/');
      var l = url.length // #TODO: NEEDS EDITING! doesn't work if # is in the link!
      url = url[l-2]
      console.log(url);
      $.ajax({
        url: '/shop/ajax/add-item-to-cart/',
        data: {
          'id': id,
          'pk': url
        },
        dataType: 'json',
        success: function (data) {
          if (data.success) {
            console.log(data.messages[0])
            console.log(data.messages[0].level)
            console.log(data.messages[0].message)
            console.log("<div class='alert alert-"+data.messages[0].tags+"'>"+data.messages[0].message+"</div>")
            update_messages(data.messages[0]);
            update_cart_items()
            
          }
        }
      });

    });
  </script>
{%endblock scripts%}

django_shop/shop/templates/shop/list_form.html
{% extends 'shop/base.html' %}  
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block extrahead %}
  {{ form.media.css }}
{% endblock extrahead %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form | crispy}}
    <button type="submit" class="btn btn-success">Save List</button>
  </form>
{% endblock %}

  {% block extra_scripts %}
  {{form.media.js}}
  <script>
  </script>
  {% endblock extra_scripts %}




{% comment %} <!DOCTYPE html>
<html>
<head>
  {{ form.media.css }}
  <style type="text/css">
    select {
      width: 200px;
    }
  </style>
</head>
<body>
<form method="post" action="">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit Form"/>
</form>
<script type="text/javascript">
  window.onerror = function (msg) {
    $("body").attr("JSError", msg);
  }
</script>
{{ form.media.js }}
</body> {% endcomment %}

django_shop/shop/templates/shop/load_cart.html
{% comment %} {{customer}}
{{customer.cart}}
{{customer.cart.list_items}} {% endcomment %}

{% for item in customer.cart.list_items.all %}
    <a class="dropdown-item" href="#">{{item.product.name}}</a>
{%endfor%}

django_shop/shop/templates/shop/start_buying_summary_page.html
{% extends 'shop/base.html' %}
{% block content %}
   <div class="row">
        <div>{{request.customer.cart.get_items}}</div>
    </div>
{% endblock %}

django_shop/shop/templates/shop/user_lists.html
{% extends "shop/base.html" %}
{% load i18n %}


{% block title %}<title>{% trans "Index Page" %}</title>{% endblock %}


{% block content %}
<div class="row">
  <div class="col-md-6 list-group">
    <h1>{{user_shown.username}}'s lists</h1>
    {% for list in lists %}
      <a href="{% url 'list-detail' list.id %}" class="list-group-item list-group-item-action list-group-item-dark">{{list.name}}</a>  
    {% endfor %}
  </div>
</div>
{% endblock content %}